### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by sadda** [Phoenix4582/CowIDentifier#1]
Hello, thanks a lot for your work on this and all previous cow datasets. I would like to ask whether it is available online. If not, do you have any estimate of when it could become so?

Best,

Lukas

**Comment by Phoenix4582** [comment]
> Hello, thanks a lot for your work on this and all previous cow datasets. I would like to ask whether it is available online. If not, do you have any estimate of when it could become so?
> 
> Best,
> 
> Lukas

Currently(Oct 31st, 2024), it is still being archived since it uses university resources. However, I will update the link as soon as it is distributed.

**Comment by sadda** [comment]
Ok, thanks a lot for the info. Please let me know when it is available. Thanks.

**Comment by Phoenix4582** [comment]
> Ok, thanks a lot for the info. Please let me know when it is available. Thanks.

Sorry for the waiting. The dataset should now be available now following this link, which itself will be used as a page for connecting both paper and dataset: https://phoenix4582.github.io/MultiCamCows2024.github.io/

**Comment by sadda** [comment]
Hi, no problem for the waiting. The download from its [website ](https://data.bris.ac.uk/data/dataset/2inu67jru7a6821kkgehxg3cv2) does not seem to work though. Both when I try to download it manually (the download does not start followed by `Secure Connection Failed`) or when I use `urllib.request.urlretrieve` (I get the error `RemoteDisconnected: Remote end closed connection without response`).

**Comment by Phoenix4582** [comment]
> Hi, no problem for the waiting. The download from its [website ](https://data.bris.ac.uk/data/dataset/2inu67jru7a6821kkgehxg3cv2) does not seem to work though. Both when I try to download it manually (the download does not start followed by `Secure Connection Failed`) or when I use `urllib.request.urlretrieve` (I get the error `RemoteDisconnected: Remote end closed connection without response`).

I just issued with the dataset team about it. While I doubt it is either about the size of the dataset(which may take some time for response), or security settings(which is what the dataset team is now checking if there are any issues). Sorry again for the inconvenience.

**Comment by Phoenix4582** [comment]
> Hi, no problem for the waiting. The download from its [website ](https://data.bris.ac.uk/data/dataset/2inu67jru7a6821kkgehxg3cv2) does not seem to work though. Both when I try to download it manually (the download does not start followed by `Secure Connection Failed`) or when I use `urllib.request.urlretrieve` (I get the error `RemoteDisconnected: Remote end closed connection without response`).

Hello again! The dataset now should be downloaded. Thank you very much for your feedback!

**Comment by sadda** [comment]
It is fine now. Thanks a lot :)
